# Generated by Django 3.1 on 2023-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('equipamentos_requisitos', models.CharField(max_length=1000)),
                ('como_fazer', models.CharField(max_length=1000)),
                ('por_que_funciona', models.CharField(max_length=1000)),
                ('tempo_estimado', models.CharField(max_length=1000)),
                ('frequencia', models.CharField(max_length=1000)),
                ('hora_do_dia', models.CharField(max_length=1000)),
                ('efeitos', models.CharField(max_length=1000)),
                ('dicas', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
    ]
