# Generated by Django 3.1 on 2023-08-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='beneficios',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='habits',
            name='descricao',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
