# Generated by Django 3.1 on 2023-07-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbsSubstances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herbssubstance',
            old_name='desvantages_cuidados',
            new_name='desvantagens_cuidados',
        ),
    ]
