# Generated by Django 3.1 on 2023-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbsSubstances', '0002_auto_20230724_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbssubstance',
            name='name',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
