# Generated by Django 3.1 on 2023-08-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
