# Generated by Django 3.1 on 2023-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10000)),
                ('action_mechanisms', models.CharField(max_length=10000)),
                ('potential_benefits', models.CharField(max_length=10000)),
                ('effects_precautions', models.CharField(max_length=10000)),
                ('gene_interactions', models.CharField(max_length=10000)),
                ('references', models.CharField(max_length=10000)),
                ('user_experience', models.CharField(max_length=10000)),
                ('scientific_studies', models.CharField(max_length=10000)),
                ('faq', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'saude',
            },
        ),
    ]
