# Generated by Django 3.1 on 2023-07-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doenca',
            old_name='faq_doença',
            new_name='faq_doenca',
        ),
    ]
