# Generated by Django 3.1 on 2023-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=1000)),
                ('composicao', models.CharField(max_length=100)),
                ('usos', models.CharField(max_length=1000)),
                ('contra_indicacoes', models.CharField(max_length=1000)),
                ('doencas_situacoes', models.CharField(max_length=1000)),
                ('faq', models.CharField(max_length=1000)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
