# Generated by Django 3.1 on 2023-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='nome',
            new_name='nome_cientifico',
        ),
        migrations.AddField(
            model_name='medicines',
            name='classe_droga',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='medicines',
            name='nome_comercial',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='medicines',
            name='principio_ativo',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='composicao',
            field=models.CharField(max_length=1000),
        ),
    ]
