# Generated by Django 3.1 on 2023-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20230802_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='classe_medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='consulta_medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=1000)),
                ('main_active', models.CharField(max_length=1000)),
                ('register', models.CharField(max_length=1000)),
                ('preccess', models.CharField(max_length=1000)),
                ('cpnj', models.CharField(max_length=1000)),
                ('situation', models.CharField(max_length=1000)),
                ('maturity', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'consulta_medicamentos',
            },
        ),
    ]
