# Generated by Django 3.1 on 2023-08-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_classe_medicamentos_consulta_medicamentos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classe_medicamentos',
            table='clase_medicamentos',
        ),
    ]
